name: Github iQIYI-DailyBonus

on:
  push:
    branches:
      - master
  watch:
    types: started
  schedule:
    - cron: '15 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run app
        run: npm install
      - run: node app.js
        env:
          iQIYI_COOKIE: ${{ secrets.iQIYI_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
